### ISSUE TITLE
Summer Internship Program Setup

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/community-engagement-outreach#12]
Activities associated with the DataONE Summer Internship.
- [x] Solicit proposals from within DataONE
- [x] Review proposals
- [x] Create registration form
- [x] Update web page
- [x] Open call for applications
- [x] Advertise opportunity (repeat)
- [x] Evaluate applicants
- [x] Consult with mentor teams
- [x] Make offers
- [x] Send out regrets
- [ ] Develop Mentoring Plan document
- [x] Support face-to-face meeting logistics
- [x] Implment mid-term survey
- [x] Implement end of internship survey
- [ ] Complete SIP report

**Comment by meg3mach** [comment]
https://www.dataone.org/internships#project2

**Comment by aebudden** [comment]
CEO specific internships are located in other tickets

**Comment by aebudden** [comment]
Postcards in pdf and jpeg format created for circulation.
[SummerInternship2018.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6b8f2122cf6d00119ba36c/125516c66e82c728ace21e0d46db81972e87918081fdba51aa4ef89d391477227146ef696097ec22ba416f43554d4bfd495f5f12fffed878f7b63e758a5c0abc843b5775906c03b0aac04ee155e57dd205d0f4ae805ec1e03724e28a864d3b1b021c8afa5433b2d4.pdf)
![SummerInternship2018.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6b8f2122cf6d00119ba36c/125516c66e82c728ace21e0d46db81972e87918081fdba51aa4ef89d391477227146ef696097ec22ba416f43554d4bfd495f5f12fffed878f7b63e758a5c0abc843b5775906c03b0aac04ee155e57dd205d0f4ae805ec1e13724e28a864d3b1b021d88ff5b33b2d4.jpg)

**Comment by aebudden** [comment]
Promoted via website, social media (FB and Twitter), to DataONE, ESIP and ecolog listserves. Please promote and list additional listserves / venues below.

**Comment by mbjones** [comment]
Completed.
