### ISSUE TITLE
March - Webinar Prep

### ISSUE THREAD

**Issue by meg3mach** [DataONEorg/community-engagement-outreach#15]
- [x] Identify Speaker
- [x] Solicit Materials (Title, Abstract, Bio)
- [x] Create registration page
- [x] Create ical
- [x] Load to website
- [x] Promote webinar
- [x] Set up test run

**Comment by meg3mach** [comment]
- [x] Identify Speaker
- [x] Solicit Materials (Title, Abstract, Bio)
- [x] Create registration page
- [x] Create ical
- [x] Load to website
- [ ] Promote webinar
- [ ] Set up test run

**Comment by aebudden** [comment]
See also issues #15 and #16

**Comment by meg3mach** [comment]
Stephanie Simms does not want to do a practice. She will be online at 830am before the webinar on Tuesday.
