### ISSUE TITLE
March 2-pager updates

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/community-engagement-outreach#2]
Link to 2pager metrics update instructions: https://drive.google.com/file/d/1-7Hgouu9CpHiHMycSiwsmRklkos-cRf0/view?usp=sharing

Update list: 
- [ ] Run R code to update (1) member node plot, (2) repository data and metadata count plots, and (3) member node and repository data count table with current and one year ago counts
- [ ] Run R code to update data heat map
- [ ] Open most recent .indd file and update heat map and plot links
- [ ] Plots of member nodes and data/metadata
- [ ] Data counts calculated in MetricsTotalsTable.csv (found in Repository_Data folder)
- [ ] Metrics from users, Funder only
- [ ] Current member node list
- [ ] Heatmap of global data count
- [ ] Month and Year in bottom right corner of each two-pager

**Comment by meg3mach** [comment]
The layout .indd file for the two-pager is updated - https://drive.google.com/file/d/1ckmaM6rfeTf6IbAH1sofWDW6Yng-G2Zj/view

**Comment by meg3mach** [comment]
The high-quality PDF for the March Quarterly update can be found: https://drive.google.com/open?id=1LqRmygVyahB2IT9ti5wVwneJ2z1VuEnH

**Comment by aebudden** [comment]
TERN made a logo change - to be included in next iteration

**Comment by aebudden** [comment]
Some logos are different to those used on our dashboard and search interface (GLEON - going away), Gulf of Mexico. We should be consistent with those resources.

**Comment by aebudden** [comment]
LT voted to call the 'contributors category' "Contributing Data Repository/Repositories"

**Comment by meg3mach** [comment]
What is the "contributors category"? The right hand column on the back? And do you want me to write "repository/repositories"?

**Comment by meg3mach** [comment]
Just did final update of 2-pager, it now has a map with red tones instead of pink for the Funders, and I noticed the data/metadata plots were faded looking. They now look nice and bright.
