### ISSUE TITLE
CEO Summer Internship Project: Synthesis Science and DataONE

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/community-engagement-outreach#22]
This is the issue associated with the "Supporting Synthesis Science with DataONE" project. Leads are Megan and Amber. Please 'assign' yourself if you wish to be part of he mentor team for this project.
Project details can be found at: 
https://www.dataone.org/internships#project2

**Comment by meg3mach** [comment]
-[ ] to do 
-[ ] and this

**Comment by mbjones** [comment]
No longer applicable
