### ISSUE TITLE
AHM Agenda

### ISSUE THREAD

**Issue by aebudden** [DataONEorg/community-engagement-outreach#31]
https://docs.google.com/spreadsheets/d/1-vSzKZF_Ds2slZS4Ah6RKB9Jso2FKxAK1DI6ojxUVDE/edit#gid=0

CEO agenda developed. Need to link with other WGs for cross activity.

**Comment by aebudden** [comment]
Agenda within CEO folders: https://docs.google.com/spreadsheets/d/1CHRmnX7EObj4VgMzKqwAXgnvLg-J_Acr8zTuF3ljUIg/edit#gid=516710794

**Comment by meg3mach** [comment]
Megan to work on a .doc agenda (add link here) and material creation for each project.

**Comment by aebudden** [comment]
Amber to follow up with U&A on scheduling

**Comment by mbjones** [comment]
Completed.
